services:
  dev-gip:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - /opt/configs/graphprotocol/gip.env
    user: "vscode"
    volumes:
      # Git repo root
      - /git:/git
